# Generated by Django 3.0.2 on 2020-07-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotmonitor', '0002_typeofthing'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofthing',
            name='name_of_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iotmonitor.Thing'),
            preserve_default=False,
        ),
    ]
