# Generated by Django 3.0.2 on 2020-07-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotmonitor', '0003_typeofthing_name_of_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofthing',
            name='name_of_type',
        ),
        migrations.AddField(
            model_name='thing',
            name='name_of_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iotmonitor.TypeOfThing'),
            preserve_default=False,
        ),
    ]
