# Generated by Django 3.0.2 on 2020-07-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotmonitor', '0005_auto_20200716_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='type',
            new_name='type_of_thing',
        ),
    ]
