# Generated by Django 3.0.2 on 2020-07-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotmonitor', '0006_auto_20200716_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='typeofthing',
            name='published_date',
        ),
    ]
